version: 0.2
env:
    secrets-manager:
        DOCKER_HUB_ACCESS_TOKEN: opslevel-interview:docker_hub_access_token
phases:
    build:
        commands:
        -   tag="$ECR_REPOSITORY:git-$CODEBUILD_RESOLVED_SOURCE_VERSION"
        -   docker login -u staschuk -p "$DOCKER_HUB_ACCESS_TOKEN"
        -   docker build src -t "$tag"
        -   $(aws ecr get-login --no-include-email)
        -   docker push "$tag"
