AWSTemplateFormatVersion: "2010-09-09"
Description: Build resources for the Hello service

Resources:

    Project:
        Type: AWS::CodeBuild::Project
        Properties:
            Artifacts:
                Type: NO_ARTIFACTS
            Description: Hello service Docker container
            Name: hello-build
            Source:
                Type: GITHUB
                Location: https://github.com/stebulus/hello-svc
            Triggers:
                Webhook: true
                FilterGroups:
                -   -   Type: EVENT
                        Pattern: PUSH
                    -   Type: HEAD_REF
                        Pattern: "^refs/heads/dev$"
            ServiceRole: !Ref BuildRole
            Environment:
                Type: LINUX_CONTAINER
                ComputeType: BUILD_GENERAL1_SMALL
                Image: aws/codebuild/standard:4.0
                PrivilegedMode: true  # so it can build docker images
                EnvironmentVariables:
                -   Name: ECR_REPOSITORY
                    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}

    Repository:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: hello

    BuildRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                            codebuild.amazonaws.com
                    Action:
                        - sts:AssumeRole
            Policies:
            -   PolicyName: HelloCodeBuildServiceRole
                PolicyDocument:
                    # suitable permissions according to
                    # https://docs.aws.amazon.com/codebuild/latest/userguide/setting-up.html#setting-up-service-role
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Sid": "CloudWatchLogsPolicy",
                          "Effect": "Allow",
                          "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                          ],
                          "Resource": [
                            "*"
                          ]
                        },
                        {
                          "Sid": "CodeCommitPolicy",
                          "Effect": "Allow",
                          "Action": [
                            "codecommit:GitPull"
                          ],
                          "Resource": [
                            "*"
                          ]
                        },
                        {
                          "Sid": "S3GetObjectPolicy",
                          "Effect": "Allow",
                          "Action": [
                            "s3:GetObject",
                            "s3:GetObjectVersion"
                          ],
                          "Resource": [
                            "*"
                          ]
                        },
                        {
                          "Sid": "S3PutObjectPolicy",
                          "Effect": "Allow",
                          "Action": [
                            "s3:PutObject"
                          ],
                          "Resource": [
                            "*"
                          ]
                        },
                        {
                          "Sid": "ECRPullPolicy",
                          "Effect": "Allow",
                          "Action": [
                            "ecr:BatchCheckLayerAvailability",
                            "ecr:GetDownloadUrlForLayer",
                            "ecr:BatchGetImage"
                          ],
                          "Resource": [
                            "*"
                          ]
                        },
                        {
                          "Sid": "ECRAuthPolicy",
                          "Effect": "Allow",
                          "Action": [
                            "ecr:GetAuthorizationToken"
                          ],
                          "Resource": [
                            "*"
                          ]
                        },
                        {
                          "Sid": "S3BucketIdentity",
                          "Effect": "Allow",
                          "Action": [
                            "s3:GetBucketAcl",
                            "s3:GetBucketLocation"
                          ],
                          "Resource": 
                            "*"
                        }
                      ]
                    }
