AWSTemplateFormatVersion: "2010-09-09"
Description: Load balancer for the Hello service

Parameters:

    EnvironmentName:
        Type: String

Outputs:

    LoadBalancer:
        Value: !Ref LoadBalancer
        Export:
            Name: !Sub hello-${EnvironmentName}-lb

    TargetGroup:
        Value: !Ref TargetGroup
        Export:
            Name: !Sub hello-${EnvironmentName}-target-group

    SecurityGroup:
        Value: !Ref LBSecurityGroup
        Export:
            Name: !Sub hello-${EnvironmentName}-lb-sg

Resources:

    # redirect http requests to https
    HTTPListener:
       Type: AWS::ElasticLoadBalancingV2::Listener
       Properties:
         LoadBalancerArn: !Ref LoadBalancer
         Port: 80
         Protocol: HTTP
         DefaultActions:
           -   Type: redirect
               RedirectConfig:
                   Protocol: HTTPS
                   Port: "443"
                   Host: "#{host}"
                   Path: "/#{path}"
                   Query: "#{query}"
                   StatusCode: "HTTP_301"  # i.e., permanent

    HTTPSListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 443
            Protocol: HTTPS
            DefaultActions:
            -   Type: fixed-response
                FixedResponseConfig:
                    StatusCode: "444"
            Certificates:
            -   CertificateArn: !Ref Certificate

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Type: application
            SecurityGroups:
            -   !Ref LBSecurityGroup
            Subnets:
            -   Fn::ImportValue:
                    !Sub "hello-${EnvironmentName}-subnet1"
            -   Fn::ImportValue:
                    !Sub "hello-${EnvironmentName}-subnet2"

    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Port: 8080
            Protocol: HTTP
            VpcId:
                Fn::ImportValue:
                    !Sub "hello-${EnvironmentName}-vpc"

    LBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Load balancer
            VpcId:
                Fn::ImportValue:
                    !Sub "hello-${EnvironmentName}-vpc"
            SecurityGroupIngress:
            -   Description: Public access to HTTP port
                CidrIp: 0.0.0.0/0
                IpProtocol: tcp
                FromPort: 80
                ToPort: 80
            -   Description: Public access to HTTPS port
                CidrIp: 0.0.0.0/0
                IpProtocol: tcp
                FromPort: 443
                ToPort: 443

    Certificate:
        Type: AWS::CertificateManager::Certificate
        DependsOn: RecordSet
        Properties:
            DomainName:
                Fn::Join:
                -   .
                -   -   !Sub ${EnvironmentName}
                    -   opslevel
                    -   !ImportValue hello-base-domain
            ValidationMethod: DNS
            DomainValidationOptions:
            -   DomainName:
                    Fn::Join:
                    -   .
                    -   -   !Sub ${EnvironmentName}
                        -   opslevel
                        -   !ImportValue hello-base-domain
                HostedZoneId: !ImportValue hello-hosted-zone-id

    RecordSet:
        Type: AWS::Route53::RecordSet
        Properties:
            AliasTarget:
                DNSName: !GetAtt LoadBalancer.DNSName
                HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
            HostedZoneId: !ImportValue hello-hosted-zone-id
            Name:
                Fn::Join:
                -   .
                -   -   !Sub ${EnvironmentName}
                    -   opslevel
                    -   !ImportValue hello-base-domain
            Type: A

