AWSTemplateFormatVersion: "2010-09-09"
Description: Network for the Hello service

Parameters:

    EnvironmentName:
        Type: String

Outputs:

    Vpc:
        Value: !Ref Vpc
        Export:
            Name: !Sub hello-${EnvironmentName}-vpc

    Subnet1:
        Value: !Ref Subnet1
        Export:
            Name: !Sub hello-${EnvironmentName}-subnet1

    Subnet2:
        Value: !Ref Subnet2
        Export:
            Name: !Sub hello-${EnvironmentName}-subnet2

Resources:

    Subnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref Vpc
            AvailabilityZone: !Sub ${AWS::Region}a
            CidrBlock: 192.168.1.0/24

    Subnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref Vpc
            AvailabilityZone: !Sub ${AWS::Region}b
            CidrBlock: 192.168.2.0/24

    Vpc:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 192.168.0.0/16

    GatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
          InternetGatewayId: !Ref Gateway
          VpcId: !Ref Vpc

    Gateway:
        Type: AWS::EC2::InternetGateway
        Properties: {}

    RouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref Vpc

    Route:
        Type: AWS::EC2::Route
        Properties:
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref Gateway
            RouteTableId: !Ref RouteTable

    Subnet1Assoc:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref RouteTable
            SubnetId: !Ref Subnet1

    Subnet2Assoc:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref RouteTable
            SubnetId: !Ref Subnet2
